### ISSUE TITLE
liens dl.free.fr défectueux

### ISSUE THREAD

**Issue by monsieurxu** [u4y0u/ZAPM_FRANCE_NRO_PMZ#1]
Bonjour, J'ai tenté de récupérer les fichiers pointés par les liens dl.free.fr mais cela ne fonctionne pas

**Comment by u4y0u** [comment]
Tout est en ligne ici dans un fichier zip complet (mise à jour chaque semaine sauf cas particulier)
https://www.data.gouv.fr/fr/datasets/r/cdb4c712-8e2c-490d-9fd3-ba5dfdf2f033
les fichiers une fois extraits sont utilisables directement sur QGIS (pc) ou QField (appli android).
